[package]
name = "librespot-metadata"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies]
byteorder = "1.3"
futures = "0.1"
linear-map = "1.2"
protobuf = "2.8.*"

[dependencies.librespot-core]
path = "../core"
[dependencies.librespot-protocol]
path = "../protocol"
