language: rust
rust:
  - 1.15.0
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
      - libc6-dev-armhf-cross
      - libpulse-dev
      - portaudio19-dev

before_script:
    - mkdir -p ~/.cargo
    - echo '[target.armv7-unknown-linux-gnueabihf]' > ~/.cargo/config
    - echo 'linker = "arm-linux-gnueabihf-gcc"' >> ~/.cargo/config
    - rustup target add armv7-unknown-linux-gnueabihf

script:
    - cargo build --no-default-features --features "with-rust-mdns"
    - cargo build --no-default-features --features "with-rust-mdns with-tremor"
    - cargo build --no-default-features --features "with-rust-mdns portaudio-backend"
    - cargo build --no-default-features --features "with-rust-mdns pulseaudio-backend"
    - cargo build --no-default-features --features "with-rust-mdns alsa-backend"
    - cargo build --no-default-features --target armv7-unknown-linux-gnueabihf --features "with-rust-mdns"

notifications:
    email: false
