language: rust
rust:
  - stable
  - beta
  - nightly-2016-03-17 # Last known to be working nightly
  - nightly

addons:
  apt:
    packages:
      - libprotoc-dev
      - portaudio19-dev
      - libpulse-dev 
      
script:
    - cargo build --no-default-features --features "with-syntex"
    - cargo build --no-default-features --features "with-syntex with-tremor"
    - cargo build --no-default-features --features "with-syntex facebook"
    - cargo build --no-default-features --features "with-syntex portaudio-backend"
    - cargo build --no-default-features --features "with-syntex pulseaudio-backend"
    - cargo build --no-default-features --features "with-syntex syslog-output"
    # Building without syntex only works on nightly
    - if [[ $TRAVIS_RUST_VERSION == *"nightly"* ]]; then
        cargo build --no-default-features;
      fi

matrix:
  allow_failures:
    - rust: nightly
