[package]
name = "librespot"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies.librespot-protocol]
path = "protocol"

[dependencies]
mod_path = "*"
byteorder = "*"
num = "*"
rand = "*"
lazy_static = "0.1.*"
rust-crypto = "*"
time = "*"
tempfile = "*"
rpassword = "*"
getopts = "0.2.4"
log = "0.3"
env_logger = "0.3"

[dependencies.protobuf]
git = "https://github.com/plietar/rust-protobuf.git"
[dependencies.protobuf_macros]
git = "https://github.com/plietar/rust-protobuf-macros.git"
[dependencies.rust-gmp]
git = "https://github.com/plietar/rust-gmp.git"
[dependencies.shannon]
git = "https://github.com/plietar/rust-shannon.git"
[dependencies.readall]
git = "https://github.com/plietar/rust-readall.git"
[dependencies.portaudio]
git = "https://github.com/mvdnes/portaudio-rs"
[dependencies.vorbis]
git = "https://github.com/plietar/vorbis-rs"

[build-dependencies]
vergen = "*"
