[package]
name = "librespot"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"
license = "MIT"
description = "Open Source Spotify client library"
keywords = ["spotify"]
repository = "https://github.com/plietar/librespot"
readme = "README.md"

[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "librespot"
path = "src/main.rs"

[dependencies.librespot-protocol]
path = "protocol"

[dependencies]
extprim         = "~1.1.0"
bit-set         = "~0.4.0"
byteorder       = "~0.5.1"
eventual        = "~0.1.6"
getopts         = "~0.2.14"
hyper           = { version = "0.9.1", default-features = false }
#json_macros     = "~0.3.0"
lazy_static     = "~0.2.0"
linear-map      = "1.0"
lmdb-rs         = "0.7.2"
num             = "~0.1.30"
protobuf        = "~1.0.15"
rand            = "~0.3.13"
rpassword       = "~0.2.2"
rust-crypto     = "~0.2.34"
rustc-serialize = "~0.3.16"
serde           = "0.7"
serde_json      = "0.7"
serde_macros    = { version = "0.7", optional = true }
tempfile        = "~2.1.3"
url             = "~0.5.0"
log             = "0.3.5"
env_logger      = "0.3.2"
shannon         = { git = "https://github.com/plietar/rust-shannon" }

vorbis          = "~0.0.14"
tremor          = { git = "https://github.com/plietar/rust-tremor", optional = true }

alsa            = { git = "https://github.com/plietar/rust-alsa", optional = true }
portaudio       = { git = "https://github.com/mvdnes/portaudio-rs", optional = true }
libpulse-sys    = { git = "https://github.com/astro/libpulse-sys", optional = true }

json_macros     = { git = "https://github.com/plietar/json_macros" }
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }

clippy          = { version = "*", optional = true }

openssl         = { version = "0.7", optional = true }

mdns            = { git = "http://github.com/plietar/rust-mdns" }

[build-dependencies]
vergen          = "~0.1.0"
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }
json_macros     = { git = "https://github.com/plietar/json_macros" }
serde_codegen   = { version = "0.7", optional = true }

[features]
with-syntex       = ["serde_codegen", "protobuf_macros/with-syntex", "json_macros/with-syntex"]
nightly           = ["serde_macros"]

with-tremor       = ["tremor"]
facebook          = ["hyper/ssl", "openssl"]
alsa-backend      = ["alsa"]
portaudio-backend = ["portaudio"]
pulseaudio-backend= ["libpulse-sys"]
default           = ["with-syntex", "portaudio-backend"]

[package.metadata.deb]
maintainer = "nobody"
copyright = "2016 Paul Liétar"
license_file = ["LICENSE", "4"]
depends = "$auto"
extended_description = """\
librespot is an open source client library for Spotify. It enables applications \
to use Spotify's service, without using the official but closed-source \
libspotify. Additionally, it will provide extra features which are not \
available in the official library."""
section = "sound"
priority = "optional"
assets = [
    ["target/release/librespot", "usr/bin/", "755"]
]
