
[target.aarch64-linux-android]
ar = "/home/mat/Android/Sdk/ndk-standalone-aarch64/bin/aarch64-linux-android-ar"
linker = "/home/mat/Android/Sdk/ndk-standalone-aarch64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/home/mat/Android/Sdk/ndk-standalone-arm/bin/arm-linux-androideabi-ar"
linker = "/home/mat/Android/Sdk/ndk-standalone-arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/home/mat/Android/Sdk/ndk-standalone-x86/bin/i686-linux-android-ar"
linker = "/home/mat/Android/Sdk/ndk-standalone-x86/bin/i686-linux-android-clang"
