[package]
name = "librespot"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "librespot"
path = "src/main.rs"

[dependencies.librespot-protocol]
path = "protocol"

[dependencies]
bit-set         = "~0.4.0"
byteorder       = "~0.5.1"
eventual        = "~0.1.6"
getopts         = "~0.2.14"
hyper           = { version = "0.9.1", default-features = false }
#json_macros     = "~0.3.0"
lazy_static     = "~0.2.0"
linear-map      = "1.0"
lmdb-rs         = "0.7.0"
num             = "~0.1.30"
protobuf        = "~1.0.15"
rand            = "~0.3.13"
rpassword       = "~0.2.2"
rust-crypto     = "~0.2.34"
rustc-serialize = "~0.3.16"
serde           = "0.7"
serde_json      = "0.7"
serde_macros    = { version = "0.7", optional = true }
tempfile        = "~2.1.3"
time            = "~0.1.34"
url             = "~0.5.0"
log             = "0.3.5"
env_logger      = "0.3.2"
shannon         = { git = "https://github.com/plietar/rust-shannon" }

vorbis          = { version = "~0.0.14", optional = true }
tremor          = { git = "https://github.com/plietar/rust-tremor", optional = true }

portaudio       = { git = "https://github.com/mvdnes/portaudio-rs", optional = true }
libpulse-sys    = { git = "https://github.com/astro/libpulse-sys", optional = true }

json_macros     = { git = "https://github.com/plietar/json_macros" }
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }

clippy          = { version = "*", optional = true }

openssl         = { version = "0.7", optional = true }

mdns            = { git = "http://github.com/plietar/rust-mdns" }

[build-dependencies]
vergen          = "~0.1.0"
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }
json_macros     = { git = "https://github.com/plietar/json_macros" }
serde_codegen   = { version = "0.7", optional = true }

[features]
with-syntex       = ["serde_codegen", "protobuf_macros/with-syntex", "json_macros/with-syntex"]
nightly           = ["serde_macros"]

with-tremor       = ["tremor"]
facebook          = ["hyper/ssl", "openssl"]
portaudio-backend = ["portaudio"]
pulseaudio-backend= ["libpulse-sys"]
default           = ["with-syntex", "portaudio-backend", "vorbis"]
