[package]
name = "librespot"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "librespot"
path = "src/main.rs"

[dependencies.librespot-protocol]
path = "protocol"

[dependencies]
bit-set         = "~0.2.0"
byteorder       = "~0.4.2"
eventual        = "~0.1.5"
getopts         = "~0.2.14"
hyper           = { version = "0.7.2", default-features = false }
#json_macros     = "~0.3.0"
lazy_static     = "~0.1.15"
lmdb-rs         = "0.7.0"
num             = "~0.1.30"
protobuf        = "~1.0.15"
rand            = "~0.3.13"
rpassword       = "~0.1.1"
rust-crypto     = "~0.2.34"
rustc-serialize = "~0.3.16"
tempfile        = "~2.0.0"
time            = "~0.1.34"
url             = "~0.5.2"
vorbis          = "~0.0.14"

dns-sd          = { version  = "~0.1.1", optional = true }

portaudio       = { git = "https://github.com/mvdnes/portaudio-rs" }

json_macros     = { git = "https://github.com/plietar/json_macros" }
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }
shannon         = { git = "https://github.com/plietar/rust-shannon" }
tremor          = { git = "https://github.com/plietar/rust-tremor", optional = true }

clippy          = { version = "*", optional = true }

openssl         = { version = "0.7", optional = true }

libpulse-sys	= { git = "https://github.com/astro/libpulse-sys" }

[build-dependencies]
vergen          = "~0.1.0"
syntex          = { version = "*", optional = true }
protobuf_macros = { git = "https://github.com/plietar/rust-protobuf-macros" }
json_macros     = { git = "https://github.com/plietar/json_macros" }

[features]
discovery     = ["dns-sd"]
with-syntex   = ["syntex", "protobuf_macros/with-syntex", "json_macros/with-syntex"]
with-tremor   = ["tremor"]
#facebook      = ["hyper/ssl", "openssl"]
static-appkey = []
pulseaudio-sink = []
portaudio-sink = []
default       = ["with-syntex","portaudio-sink"]
