[package]
name = "librespot-core"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]
build = "build.rs"

[dependencies.librespot-protocol]
path = "../protocol"

[dependencies]
base64 = "0.10"
byteorder = "1.3"
bytes = "0.4"
error-chain = { version = "0.12", default_features = false }
extprim = "1.7"
futures = "0.1"
httparse = "1.3"
hyper = "0.11"
hyper-proxy = { version = "0.4", default_features = false }
lazy_static = "1.3"
log = "0.4"
num-bigint = "0.2"
num-integer = "0.1"
num-traits = "0.2"
protobuf = "2.8.*"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shannon = "0.2.0"
tokio-codec = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
url = "1.7"
uuid = { version = "0.7", features = ["v4"] }
sha-1 = "0.8"
hmac = "0.7"
pbkdf2 = "0.3"
aes = "0.3"

[build-dependencies]
rand = "0.7"
vergen = "0.1.0"
