[package]
name = "librespot-audio"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies.librespot-core]
path = "../core"

[dependencies]
bit-set = "0.5"
byteorder = "1.3"
futures = "0.1"
lewton = "0.9"
log = "0.4"
num-bigint = "0.2"
num-traits = "0.2"
tempfile = "3.1"
aes-ctr = "0.3"

tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
vorbis = { version ="0.1.0", optional = true }

[features]
with-tremor = ["tremor"]
with-vorbis = ["vorbis"]
