[package]
name = "librespot-connect"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies.librespot-core]
path = "../core"
[dependencies.librespot-playback]
path = "../playback"
[dependencies.librespot-protocol]
path = "../protocol"

[dependencies]
base64 = "0.10"
futures = "0.1"
hyper = "0.11"
log = "0.4"
num-bigint = "0.2"
protobuf = "2.8.*"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
url = "1.7"
sha-1 = "0.8"
hmac = "0.7"
aes-ctr = "0.3"
block-modes = "0.3"

dns-sd = { version = "0.1.3", optional = true }
mdns = { git = "https://github.com/plietar/rust-mdns", optional = true }

[features]
default = []
with-dns-sd = ["dns-sd"]
